### ISSUE TITLE
Can PRoot be used to access a Linux distribution from external storage such as an SD card?

### ISSUE THREAD

**Issue by SDRausty** [TermuxArch/TermuxArch#3]
@JanuszChmiel created an issue at https://github.com/termux/proot/issues/50 Can Proot be used to access Linux distribution from external storage such as SD card #50

Answer; It is possible to deposit a substantial portion of the system to external micro sdcard.  However, it is probably not worth the effort for a number of reasons including the fact that the overall saving in space is not that great.  Also,  the system that is partially in external sdcard is almost impossible to update.

**Comment by JanuszChmiel** [comment]
Thank you very much for yours explanation. I must accept The fact, that Linux and Android kernel are different and even if Android kernel support some device such as SD CARD or even USB external harddisk, I can not simply access it like from Linux. So device would be simply formatted as EXT4 and used on non rooted device.
By other words, Android manages storage fifferently. Only internal flash chips build in to Android devices are formatted and used by Android kernel similarly like in Linux.
But no problem, i allready have newer phone with 64 GB of internal storage so I can safely experiment with Proot and Linux distros.

**Comment by SDRausty** [comment]
> But no problem, i allready have newer phone with 64 GB of internal storage so I can safely experiment with Proot and Linux distros.

>  so deeply sad, that creators of my phone model have formateed EXT4 file system as case file insensitive file system. So I can not use
Ref: https://github.com/BuildAPKs/buildAPKs/issues/13

@JanuszChmiel can you please explain the dissonance in your messages?

**Comment by JanuszChmiel** [comment]
I Am very sorry for my sad dissonance on my messages.
It is caused by The fact, that I thought, that I will be able to use 4 GB of RAm of Huavei phone for this purposes. It was my big dream and I think, that it will not come true.

I will not intrude you with my sad emotions, since it will only demotivate developers from complex C programming and it will not help. I Am very sorry for that I will not make you sad and others.

**Comment by SDRausty** [comment]
@JanuszChmiel computer teachers have taught me that computer science is a manmade creation.  Therefore, it is under our complete control, as oppossed to other fields of knowledge, for instance like the weather and history.  

> It was my big dream and I think, that it will not come true.

Thus outcome you believe shall probably come true if you believe so;  If computer science is a manmade creation and it is under our complete control, what rational can you present to defend your belief?

**Comment by JanuszChmiel** [comment]
But powerful kernel do not allow Me to use Linux distributions for some complex reason. Which is not exactly known.
The problem is that also some Samsung phone models do not allow to run Linux distros by using Proot or those distros can not be installed.
May be, that manufacturers are being afraid, that Proot can be used to extract their .rc scripts which controls The phone and that somebody will extract all data and will make his own custom firmware.

**Comment by aditiyaaz** [comment]
PKG update

**Comment by SDRausty** [comment]
@aditiyaaz can you please explain what you mean by:
> PKG update

**Comment by JanuszChmiel** [comment]
As I currently know, it is impossible. Because Android uses special build in
APIS to work with special encryption key. This key encrypts private app data
on external SD cards for example. To prevent data stealing when some user
would steal SD cart and put it to his device for example.
Unfortunately, even Android is based on Linux kernel, even The kernel
differs and apps are driven by other higher modules. Sure. Somebody would
try to develop special .so library, which would be controlled by Proot. This
.so library could driver specific external USB storage such as Adata
harddisk or WDelements drives.
In this case, may be, that Proot C ccode would communicate with The lmited
number of USB external peripherals.
But even this approach his big disadvantage.
Many Android devices do not allow user to use one USB micro connector for
charging The device and to use this connector with some USB external
devices.
Even USB hubs with AC adapters are not a source of miracle solution in this
case.
Only experienced electrycian specialized on a weak streams can extend some
Android device with second AC source connector.
By other words. The only one realistic solution is to save some money and
buy more expensive devices with big internal storage.
I have used specialized bazar which offer cheap mobile phones, which have
been allready used before.
I could never buy some device with 64 GB of internal storage and with 4 GB
of RAM.
 
Next true is, that internal storage can be much more faster than The fastest
SD card available on The market thanks to other electryc circuits which are
being used to communicate with The SD card chips.

**Comment by SDRausty** [comment]
> Next true is, that internal storage can be much more faster than The fastest
SD card available on The market thanks to other electryc circuits which are
being used to communicate with The SD card chips.

Space is also a very interesting factor too.  It appears that device storage is much more efficient, when it comes to allocation of allocated space on device.  Do you agree?

**Comment by JanuszChmiel** [comment]
Yes, I agree with you.
 
The very important condition is that all used Proot system calls are
implemented correctly in The used Android kernel. And that partial case file
insensitive file system is being presented on The device.
Unfortunately, if data encryption is enabled and can not be disabled from
Android settings, this real time encryption and decryption of data inside
flash chips can make also some little slow down.
Unfortunately, Lenovo often enable data encryption inside flash chips and
device can not be decrypted and encryption can not be disabled if somebody
do not want to root such devices.
