### ISSUE TITLE
I can't set up SSH server in termuxArch

### ISSUE THREAD

**Issue by barinov274** [TermuxArch/TermuxArch#65]
I installed openssh but the service doesn't start. I tried to run "systemctl start sshd" but then It wrote to me "failed to connect to bus". 
I found out that It doesn't work because the system didn't boot systemd. I downloaded this https://github.com/gdraheim/docker-systemctl-replacement/blob/master/files/docker/systemctl3.py and then replaced with /usr/bin/systemctl.
This systemctl doesn't work too. 
```
[root@localhost ~]# systemctl start sshd
[root@localhost ~]# systemctl status sshd
sshd.service - OpenSSH Daemon
    Loaded: loaded (/usr/lib/systemd/system/sshd.service, enabled)
    Active: failed (failed)
```
How can I set up ssh server, ftp server e.t.c without systemctl? It there a way to make sytemctl work?

**Comment by SDRausty** [comment]
>a way to make sytemctl work?

The TermuxArch command `csystemctl` installs a `systemctl` replacement that seems to work as expected.

**Comment by short-circuit** [comment]
Hi,
can you please release a full instruction on how to get SSH server + XSDL and X11 forwarding working? None of the the other Issues helped since it has been quite some time and a lot of stuff broke/changed since. Systemctl replacement also still does not start sshd.service with following log:
```
sshd.service - OpenSSH Daemon
    Loaded: loaded (/usr/lib/systemd/system/sshd.service, enabled)
    Active: failed (failed)
```

Thank you.
