### ISSUE TITLE
 TermuxArch WARNING:  Generated script signal 127 near or at line number 623 by '_ADDMOTD_'! Please run 'bash setupTermuxArch.bash' again or use 'bash setupTermuxArch.bash refresh'.

### ISSUE THREAD

**Issue by JanuszChmiel** [TermuxArch/TermuxArch#70]
I have found one bug inside scripts when running Setuptermuxarch.bash script. It is new error and it has never appeared before.

Here are The outputs

Signal generated in 'proot _PREPROOT_  necessaryfunctions.bash'; Cannot complete task; Continuing...

If you find improvements for 'setupTermuxArch.bash' please open an issue and an accompanying pull request.  A pull request can assist in shedding more light on an issue.

 đź•› > đź•™ Cleaning up installation files: DONE

 đź•› > đź•¤ Arch Linux in Termux PRoot is installed.  Configuring and updating Arch Linux đź“˛  necessaryfunctions.bash: line 623: _ADDMOTD_: command not found

 TermuxArch WARNING:  Generated script signal 127 near or at line number 623 by '_ADDMOTD_'!
Please run 'bash setupTermuxArch.bash' again or use 'bash setupTermuxArch.bash refresh'.

The command 'bash setupTermuxArch.bash help' has information how to use 'setupTermuxArch.bash'.
The command 'bash setupTermuxArch.bash help' has information how to use 'setupTermuxArch.bash'.

setupTermuxArch.bash  version 2.0.1443: [Exit Signal 201] DONE đźŹ

~ $
~ $

I AM using The latest up to date stable Termux version 118. And I run apt update and apt upgrade regularly to make my best so Termux is up to date.

**Comment by SDRausty** [comment]
> Here are The outputs                                                   

Thank you for opening this issue @JanuszChmiel and sharing output, and the fact the system is uptodate.  There were major changes to almost all of the base scripts in TermuxArch, and if more users will encounter this error, it should be mitigated.  Can you please try rerunning the command after the update to see whether it works as expected?

I do not see any errors at present.  The errors I did find during writing and debugging were dissimilar to the one you found and reported.   Thank you!   Is the command that you wanted run successfully on the first try; [`bash setupTermuxArch`](https://github.com/TermuxArch/TermuxArch/blob/master/setupTermuxArch)?

What is the full command you are using?

**Comment by SDRausty** [comment]
> Here are The outputs                                                   

Thank you for opening this issue @JanuszChmiel and sharing output, and the fact the system is uptodate.  There were major changes to almost all of the base scripts in TermuxArch, and if more users will encounter this error, it should be mitigated.  Can you please try rerunning the command after the update to see whether it works as expected?

I do not see any errors at present.  The errors I did find during writing and debugging were dissimilar to the one you found and reported.   Thank you!   Is the command that you wanted run successfully on the first try; [`bash setupTermuxArch`](https://github.com/TermuxArch/TermuxArch/blob/master/setupTermuxArch)?

a) What is the full command you are using?
b) Can you please try rerunning the command after the update to see whether it works as expected?

**Comment by SDRausty** [comment]
```
Setting locales to: Language >> en_US << Region: Please wait a moment.
archlinuxconfig.bash: line 1850: CPUABIX8664: unbound variable
setupTermuxArch  2.0.1046: [Exit Signal 1] DONE 🏁
```
There was an interesting unbound [Exit Signal 1] update from a much older VERSIONID=2.0.1280 generated on armv7l with [updated packages](https://raw.githubusercontent.com/WAE/au/master/au) which are benign and seem to continually show once again that BASH code behaves as expected year after year.  I will try to make it clearer to attempt rerunning the last command if the updated version interpretted the command successfully and exited:

[`[[ -z "${ARGS:-}" ]] && printf "\\n\\e[1;32mFile \\e[0;32m'%s'\\e[1;32m was UPDATED\\e[1;34m:\\e[0;32m  Please run 'bash %s' again if this automatic update was unsuccessful.\\n\\n\\e[1;32mRESTARTED \\e[0;32m'%s'\\e[1;34m:\\e[1;32m CONTINUING...\\n\\n\\e[0m" "${0##*/}" "${0##*/}" "${0##*/}" || printf "\\n\\e[1;32mFile \\e[0;32m'%s'\\e[1;32m was UPDATED\\e[1;34m:\\e[0;32m run 'bash %s' again if this automatic update was unsuccessful;  You should be able to use the '!!' command to run '%s' again.\\n\\e[1;32mRESTARTED \\e[0;32m'%s'\\e[1;34m:\\e[1;32m CONTINUING...\\n\\n\\e[0m" "${0##*/}" "${0##*/} $ARGS" "${0##*/} $ARGS" "${0##*/} $ARGS"`](https://github.com/TermuxArch/TermuxArch/blob/master/setupTermuxArch.sh#L107)

a) ammend readme
b) ammend exit code

**Comment by SDRausty** [comment]
@JanuszChmiel I just noticed `Please run 'bash setupTermuxArch.bash' again or use 'bash setupTermuxArch.bash refresh'` so simply running `bash setupTermuxArch.bash refresh` should resolve this exit error on your machine.  Please let me know if it was unsuccessfull.

**Comment by JanuszChmiel** [comment]
But some localisation to Czech language fail even when I will run refresh option. Because Pacman and other managers are writing textual output in English.
But true is, that refresh option complete setup GPG keys are imported and some Kernel related packages are removed to prevent pacman from generating errors.
And sure, ArchLinux upgrade process also run successfully.

**Comment by SDRausty** [comment]
`🕛 > 🕗 Not removing files after checking download integrity with md5sum.   🕛 > 🕤 Arch Linux in Termux PRoot is installed.  Configuring and updating Arch Linux 📲  necessaryfunctions.bash: line 652: _ADDMOTD_: command not found`
![Screenshot_20220129-044347](https://user-images.githubusercontent.com/27742457/151656202-74cced17-5c58-4e10-aa8c-5baab08b13ee.png)

This result looks much more promising;  Hopefully I will find the time to resolve  652: _ADDMOTD_  today.

**Comment by SDRausty** [comment]
\_ADDMOTD_ WARNING resolved with https://github.com/TermuxArch/TermuxArch/commit/da0570314c6af60114082d4c65b9ac2ab28ce223  Thank you so much for shaing this issue quickly @JanuszChmiel!

**Comment by SDRausty** [comment]
You might also be interested in the new [finding external cache storage](https://github.com/shlibs/shlibs.bash/commit/87c3b5cb5d2a8c42cb08a08fc31b748a8bf8b3fe) feature that is being implemented into USECACHEDIR in `setupTermuxArchConfigs.bash`.  It might be accessable via [USECACHEDIR=1		##  change to 0 to use cache dir](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L14) in this file in the near future.

Thid feature is intended for developers to use in order to recreate the Arch Linux in Termux PRoot system easily and quickly on device from cache.  It should be used in conjunction with KEEP=0 on the initial installation of the Linux system from the Internet.  

Automated external micro sdcard storage cache is the goal.

If you have time, and more importatly space on device to use it, then please share your thoughts about the cache feature.

> localisation to Czech language fail

Is this condition still true after the fix @JanuszChmiel?

**Comment by SDRausty** [comment]
You might also be interested in the new [finding external cache storage](https://github.com/shlibs/shlibs.bash/commit/87c3b5cb5d2a8c42cb08a08fc31b748a8bf8b3fe) feature that is being implemented into USECACHEDIR in `setupTermuxArchConfigs.bash`.  It might be accessible via [USECACHEDIR=1         ##  change to 0 to use cache dir](https://github.com/Term
uxArch/TermuxArch/blob/master/knownconfigurations.bash#L14) in this file in the near future.

This feature is intended for end users and developers to use in order to recreate the Arch Linux in Termux PRoot system easily and quickly on device from cache.  It should be used in conjunction with KEEP=0 on the initial installation of the Linux system from the Internet.

Automated external micro sdcard storage cache is a goal still to be achieved.  Hopefully, it will be soon.

PRs requested at https://github.com/shlibs/shlibs.bash/pulls and https://github.com/shlibs/shlibs.sh/pulls and https://github.com/TermuxArch/TermuxArch/pulls Please.

If you have time, and more importantly space on device to use it, then please share your thoughts about this cache feature intended for system restoration.

> localization to Czech language fail

Is this condition still true after the [fix](https://github.com/TermuxArch/TermuxArch/commit/da0570314c6af60114082d4c65b9ac2ab28ce223)?

**Comment by SDRausty** [comment]
https://github.com/TermuxArch/TermuxArch/issues/70

**Comment by SDRausty** [comment]
> localisation to Czech language fail

If you are still having localization issues, please open a [new issue here](https://github.com/TermuxArch/TermuxArch/issues).  Also, feel free to submit a [new PR here](https://github.com/TermuxArch/TermuxArch/pulls).
