### ISSUE TITLE
qemu-x86_64": library "libdl.so" not found

### ISSUE THREAD

**Issue by yakovlevegor** [TermuxArch/TermuxArch#76]
I tried to run Arch x86_64 on my aarch64 Termux, but received this error:
`CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/qemu-x86_64": library "libdl.so" not found: needed by main executable`
with libdl.so being present in arch64 directory.

There were also error messages during installation:
`usr/bin/newuidmap: Cannot restore extended attributes on this system`
`bsdtar: Error exit delayed from previous errors.`
`Signal generated in 'proot _PREPROOT_ setupTermuxArch necessaryfunctions.bash'; Cannot complete task;`

**Comment by yakovlevegor** [comment]
There's also a follow-up error message during installation:
`TermuxArch WARNING:  Generated script signal 201 near or at line number 189 by 'CHSENMIR="$(grep'!`

**Comment by yakovlevegor** [comment]
Trying an older version 2.0.1460, the script shows a missing configuration error.

`🕛 > 🕝 Detected Android arm64-v8a 11 operating system;  Install architecture is set to x86-64.`

` 🔆 WARNING: Unknown configuration!  Did not find an architecture and operating system match in 'knownconfigurations.bash'!`

**Comment by SDRausty** [comment]
> qemu-x86_64": library "libdl.so" not found #76

Unfortunately, the currently published version is in a broken state.  Help debugging it, and PR is requested.  Thank you for sharing debugging information very much @yakovlevegor 

The command `setupTermuxArch bloom` can assist in reshaping this script.  You can hone in on the nature of the error by adding `set -x` and `echo` statements to the files in `~/TermuxArchBloom` without having to touch the original script.

**Comment by yakovlevegor** [comment]
The core of the problem was quite simple:
`getprop gsm.operator.iso-country` generates an output with a comma, in my case `ru,`. To fix this issue, I suggest you use `getprop gsm.sim.operator.iso-country` by default, it returns fine `ru` value on my device. The script **necessaryfunctions.bash** uses this value to get mirrors for a country code, and then uses value with a comma inside, which breaks the script.

Though Russian language is explicitly unset in my language settings and I use Tor proxy for all downloads through environment variables, so I suggest you should remove this command and find some better language detection mechanisms.

**Comment by SDRausty** [comment]
>breaks the script

Thank you for informing my about `getprop gsm.sim.operator.iso-country` and debugging the comma error;  I will look closer into this shortly.

Commit https://github.com/TermuxArch/TermuxArch/commit/ff2fda45a68cbf6e174607a2a9839f568fe30134 is the first published version that has completed a successfull installation on my end since an error has arrisen.  I usually strive not to publish code with errors, nor with any superfluous debug symbols.  This [commit](https://github.com/TermuxArch/TermuxArch/commit/ff2fda45a68cbf6e174607a2a9839f568fe30134) appears to be a good exception as it successfully logs into the proot system and has the debug symbols that seem to resolve a critical error:  
![Screenshot_20220206-153951](https://user-images.githubusercontent.com/27742457/152700495-1795b98b-2683-4c52-afe8-8825ecdc49d1.png)

There seems to be no easy fix for `usr/bin/newuidmap: Cannot restore extended attributes on this system
bsdtar: Error exit delayed from previous errors.` without upstream support;  You are welcome to yell upstream.  If you do please share any progress here.

**Comment by SDRausty** [comment]
>be no easy fix

**Comment by SDRausty** [comment]
>be no easy fix 

Commit https://github.com/TermuxArch/TermuxArch/commit/56fd26f8e67195b8336e7f3dcca5164c7122ef76 removes the error message
