### ISSUE TITLE
Can't figure out how to get orca running.

### ISSUE THREAD

**Issue by willbilec** [TermuxArch/TermuxArch#90]
Hi, I am visually impaired I would love to use the Orca screenreader with arch with the scripts that you have provided.
I have installed arch into termux and ran orcaconf in arch. It says it was successful.
How do I continue? 
I assume I need to start a Vnc server. when I run vncserver, it says something about a display, but when I try to use a Vnc client to connect to local host it is unable to connect saying connection refused.
What am I doing wrong?
Any help would be greatly appreciated.
Thanks.

**Comment by SDRausty** [comment]
Hello,

>ran orcaconf in arch. It says it was successful.

> a Vnc client to connect to local host it is unable to connect saying connection refused.

Thank you for sharing;  Hopefully this information will help:
>> When I have executed yours orcaconf script it have miracly installed special
opengl support for Tigervnc.
And here is my code which reliably open VNC connection by using Tigervnc.
Please really try to use it instead of official Archlinux script vncserver,
which have caused some issues.
Xvnc -localhost -geometry 1024x768 -depth 24 -SecurityTypes=None &
Sure, every one have its full freedom to start Tigervnc by his own way.
Really, shared memory routines, which are being used by Tigervnc are fully
compatible by using /dev/shm supported incorporated routines. So there is no
need to disable shared memory extension support.

>Is this the code for `orcarun`:
`Xvnc -localhost -geometry 1024x768 -depth 24 -SecurityTypes=None`

>Is the program name `orcarun` ok for what we are trying to achieve?

_Originally posted by @SDRausty in https://github.com/TermuxArch/TermuxArch/issues/36#issuecomment-723964278_

I would like to expand command `tour` and the builtin `README.md` with our wotk here;  Please share the progress you are making @willbilec in this thread.

**Comment by SDRausty** [comment]
>expand command `tour` and the builtin `README.md` with our work here;

This 'work' of expanding how clearly can behold [building APKs](https://github.com/BuildAPKs) from the command line in the computer environment we use on smartphone.

**Comment by yakovlevegor** [comment]
The command "vncserver :1" starts your server at port 5901. Have you set your desktop environment and other parameters in ".vnc/config"? Is the password properly set?

**Comment by SDRausty** [comment]
The recently undepreciated [`makeaurhelpers`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L664&&#L1054) command might also be helpfull in streamlining this issue;  Testing for `makeaurhelpers` is requested as this command  is undepreciated with recent commits and is now significantly expanded.  

Please see `makeaurhelpers help` for more information about its amazing new features that build and package Arch Linux AUR packages on handheld Android devices in Termux with PRoot and QEMU.

**Comment by SDRausty** [comment]
severe Seamonkey internet suite crash occurred #92 https://github.com/SDRausty/termux-archlinux/issues/92
